name: adventofcode2021
version: 0.1.0.0
synopsis: My solutions for the Advent Of Code 2021 challenge written in Haskell
description: https://github.com/Scriptim/AdventOfCode2021
license: MIT
license-file: LICENSE
author: Scriptim
maintainer: Scriptim <Scriptim@gmx.de>
github: Scriptim/AdventOfCode2021
extra-source-files:
  - README.md

ghc-options:
  -fwrite-ide-info
  -hiedir=.hie

dependencies:
  - base

internal-libraries:
  adventofcode:
    source-dirs: lib
    exposed-modules:
      - AdventOfCode
    dependencies:
      - criterion
      - deepseq
      - directory
      - filepath
      - hspec

executables:
  sonar-sweep:
    source-dirs: 01-sonar_sweep
    main: Main.hs
    dependencies:
      - adventofcode
  dive:
    source-dirs: 02-dive
    main: Main.hs
    dependencies:
      - adventofcode
      - deepseq
  binary-diagnostic:
    source-dirs: 03-binary_diagnostic
    main: Main.hs
    dependencies:
      - adventofcode
  giant-squid:
    source-dirs: 04-giant_squid
    main: Main.hs
    dependencies:
      - adventofcode
      - split

tests:
  sonar-sweep-test:
    source-dirs: 01-sonar_sweep
    main: Tests.hs
    ghc-options: -main-is Tests
    dependencies:
      - adventofcode
  dive-test:
    source-dirs: 02-dive
    main: Tests.hs
    ghc-options: -main-is Tests
    dependencies:
      - adventofcode
      - deepseq
  binary-diagnostic-test:
    source-dirs: 03-binary_diagnostic
    main: Tests.hs
    ghc-options: -main-is Tests
    dependencies:
      - adventofcode
  giant-squid-test:
    source-dirs: 04-giant_squid
    main: Tests.hs
    ghc-options: -main-is Tests
    dependencies:
      - adventofcode
      - split

benchmarks:
  sonar-sweep-bench:
    source-dirs: 01-sonar_sweep
    main: Benchmarks.hs
    ghc-options: -main-is Benchmarks
    dependencies:
      - adventofcode
  dive-bench:
    source-dirs: 02-dive
    main: Benchmarks.hs
    ghc-options: -main-is Benchmarks
    dependencies:
      - adventofcode
      - deepseq
  binary-diagnostic-bench:
    source-dirs: 03-binary_diagnostic
    main: Benchmarks.hs
    ghc-options: -main-is Benchmarks
    dependencies:
      - adventofcode
  giant-squid-bench:
    source-dirs: 04-giant_squid
    main: Benchmarks.hs
    ghc-options: -main-is Benchmarks
    dependencies:
      - adventofcode
      - split
